Repository jenkins-x-terraform/terraform-jx-azure, pull requests merged in 2021-06, with the labels that each got.

#6 feat: add updatebot to keep jx3-terraform-azure up to date
  .jx/updatebot.yaml
Labels: approved, lgtm, ok-to-test, size/S

#7 Update updatebot.yaml
  .jx/updatebot.yaml
Labels: approved, size/XS

#8 fix: add missing "v" to the version
  .jx/updatebot.yaml
Labels: approved, lgtm, size/XS

#9 fix: ensure the registry name is in lowercase
  requirements.tf
Labels: approved, lgtm, size/XS

#10 Add ability to use existing ACR
  main.tf
  terraform-jx-registry-acr/main.tf
  terraform-jx-registry-acr/outputs.tf
  terraform-jx-registry-acr/variables.tf
  variables.tf
Labels: approved, ok-to-test, size/M

#11 fix: add ability to customize registry rg
  main.tf
  variables.tf
Labels: approved, lgtm, ok-to-test, size/XS

#12 fix: dns output variable
  terraform-jx-azuredns/outputs.tf
Labels: approved, lgtm, ok-to-test, size/XS

#13 fix: consistent type
  terraform-jx-azuredns/outputs.tf
Labels: approved, lgtm, ok-to-test, size/XS

#14 chore: update k8s version to a supported one
  terraform-jx-cluster-aks/variables.tf
  variables.tf
Labels: approved, lgtm, ok-to-test, size/XS

#15 fix: update version stream repository instead of the terraform one
  .jx/updatebot.yaml
Labels: approved, lgtm, size/XS

#17 fix: add ability to use root apex domain
  terraform-jx-azuredns/local.tf
  terraform-jx-azuredns/main.tf
  terraform-jx-azuredns/outputs.tf
Labels: approved, lgtm, ok-to-test, size/M

#18 feat: added autoscaling and ml node
  main.tf
  terraform-jx-cluster-aks/cluster/main.tf
  terraform-jx-cluster-aks/cluster/variables.tf
  terraform-jx-cluster-aks/main.tf
  terraform-jx-cluster-aks/variables.tf
  variables.tf
Labels: approved, lgtm, ok-to-test, size/L
